language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: E2tmSgaST3MvCthNhl1vdW6SeVxrbzMUL97Ffq60CnQJuVGpabH9DA3/zSxDNLWDwSGuH1O/ymcr3uayjzpFlqWkSvMIHXCPVZlHB+peyjHnAc5i2VroWw8yBXXa62Bx5wGPKBt4A9hd1NAEpKDETJoQbCA4XIvxTNFKuhI1CNUSCFral/qRRrPC/36BO6OiblZc+v98aeP7fVK/S16SWrM77Tk1F9dkXOxnn1uj/FrK2ICBnxoCKg5YutpfOZGKjugWwG4TMqFAFJqfINJdjMzQ3QP+K/B5oP6imVvoX1eN+vaV+o29WNQ3/DqlydsewPMNcfbUaxaTa7oVurGWETAaUtTn754nGn+Y/kVVbO3iVqz5x/6L8jLOzCgabQ5/6KW57FNFTJYX+5aJX4a7npKH6BBDRvUclvJkz/Qe/0FVqNqwGwbFJ48dSJQaknEx3a5TJI/yU/jIAXSffFJTz0vVKUNzRduzl3zVAdNjfOtuKjfmxaJgK80epwQUVxnlCCo9+mreSKH5GMkYNY5uusEjzTvKAVEVJIgxYmhWpeRYB92INP53fLAMnvXNyy4mS2U5CbLVkeIH+pRSGnQDpT619/vp15pq+QgUGRbrpcMf8TL8isz/yhz48f2Yn0inh+trYkF9bt2dQi+2QmeCH73EG2e6zh4c1+CvBqZdCNI=
  app: shielded-sea-13068
  on:
    repo: Laurn17/blog-app-mongoose-challenge-solution
